FROM ubi8/ubi

LABEL description="Creating a custom httpd image"

LABEL mantainer="Ledio Cipi"

RUN yum install -y httpd 

EXPOSE 80

USER root

ENTRYPOINT ["usr/sbin/httpd"]

CMD ["-D", "FOREGROUND"]
